name: Basic validation

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build Java Project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List files (Debug)
        run: dir /s  # Toto nám v logu ukáže, kde přesně jsou vaše .java soubory

      - name: Compile Java
        run: |
          javac -d bin src/cz/test/*.java
